# Generated by Django 4.2.4 on 2023-09-06 10:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCatogarys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='catogry_imgs')),
                ('Name', models.CharField(max_length=255)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=13)),
                ('dob', models.DateField(blank=True, null=True)),
                ('Address', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=250)),
                ('designation', models.CharField(max_length=255)),
                ('profile_pic', models.FileField(upload_to='workers_pic/')),
                ('acc_activation', models.BooleanField(default=False)),
                ('avalability_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=13)),
                ('Address', models.TextField()),
                ('gender', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_pic', models.FileField(upload_to='workers_pic/')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeServices_app.country')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Problem_Description', models.TextField()),
                ('Address', models.TextField()),
                ('pin', models.CharField(max_length=10)),
                ('House_No', models.CharField(max_length=20)),
                ('landmark', models.TextField(null=True)),
                ('contact', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeServices_app.city')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeServices_app.servicecatogarys')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeServices_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('assigned_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeServices_app.workers')),
                ('requests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeServices_app.servicerequests')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('Description', models.TextField()),
                ('Date', models.DateField()),
                ('Employ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeServices_app.workers')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
